### PR TITLE
Remove out directory

### PR DESCRIPTION
**Pull request by RobLoach**
- Removes the `out` directory
- Brings in [base/.gitignore](https://github.com/bevry/base/blob/master/.gitignore) to ignore `out` for future updates

### CODE REVIEW

**Comment by stongo** [comment]
The out directory is missing from npm release 2.2.1

**Comment by RobLoach** [comment]
@Hypercubed When publishing, it is possible to use the Cakefile to handle it:

``` bash
cake install
cake prepublish
cake publish
```

This will compile the out directory prior to uploading to npm.

**Comment by Hypercubed** [comment]
I'm somewhat regretting accepting the cakefile pull request.  Cake is giving me various problems on cygwin.

That said... I was having an issue that if I don't have an existing out directory `cake compile` creates an empty `-p` directory.  I can't seam to reproduce it now.

**Comment by Hypercubed** [comment]
The command `coffee -w -o out/ -c src/` creates a `-p/` directory if `out/` doesn't exist.  Anyone know what causes this?

**Comment by RobLoach** [comment]
Running cake test isn't working on cygwin?

``` bash
node_modules/.bin/cake test
```

Think the Windows binaries might need work?
https://github.com/Hypercubed/docpad-plugin-raw/blob/master/Cakefile#L18

**Comment by Hypercubed** [comment]
Ok.  Cake is now working on cygwin after I upgraded from node v0.10.10 to v0.10.24.  As far as this pull request I'm going to hold back until the coffee script `mkdir -p` issue is fixed: https://github.com/jashkenas/coffee-script/issues/2027

**Comment by RobLoach** [comment]
Wow, looks like the last CoffeeScript version was 8 months ago. Looks like there's a discussion to get a new version out at https://github.com/jashkenas/coffee-script/issues/3141 .

In the mean time, it might be possible to target master rather than 1.6.3 in package.json.

**Comment by Hypercubed** [comment]
Is it a big deal that the `out/` directory is in the git repo?  I don't think we need to worry about this too much.  If I could finally transfer this to the DocPad org (https://github.com/Hypercubed/docpad-plugin-raw/issues/3) then someone else could handle it.

**Comment by RobLoach** [comment]
@balupton fixed this in https://github.com/docpad/docpad-plugin-raw 2.3.0 .

**Pull request closed without merging**
